/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.tec02.gui.panelGui;

import com.tec02.gui.Panelupdate;
import java.util.Collection;
import com.tec02.gui.guiInterface.IAction;

/**
 *
 * @author Administrator
 */
public class FilterUnit extends Panelupdate {

    private IAction selectedAction;
    private IAction<FilterUnit> focusGainedAction;

    /**
     * Creates new form FilterUnit
     *
     * @param label
     * @param selectedAction
     * @param focusGainedAction
     */
    public FilterUnit(String label, IAction selectedAction, IAction<FilterUnit> focusGainedAction) {
        initComponents();
        this.checkbox.setText(label);
        this.selectedAction = selectedAction;
        this.focusGainedAction = focusGainedAction;
    }

    public IAction getSelectedAction() {
        return selectedAction;
    }

    public IAction<FilterUnit> getFocusGainedAction() {
        return focusGainedAction;
    }

    public void setCheckedAble(boolean state) {
        this.checkbox.setEnabled(state);
    }

    public IAction getAction() {
        return selectedAction;
    }

    public String getItemSelected() {
        if (!this.checkbox.isSelected()) {
            return null;
        }
        return String.valueOf(this.combobox.getSelectedItem());
    }

    public void addItem(String item) {
        this.combobox.addItem(item);
    }

    public void clear() {
        this.combobox.removeAllItems();
    }

    public void addItems(Collection<String> collection) {
        clear();
        if (collection == null) {
            return;
        }
        for (String item : collection) {
            addItem(item);
        }
        if (!collection.isEmpty()) {
            this.combobox.setSelectedIndex(0);
        }
    }

    public void setSelectedAction(IAction selectedAction) {
        this.selectedAction = selectedAction;
    }

    public void setFocusGainedAction(IAction<FilterUnit> focusGainedAction) {
        this.focusGainedAction = focusGainedAction;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        combobox = new javax.swing.JComboBox<>();
        checkbox = new javax.swing.JCheckBox();

        combobox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboboxItemStateChanged(evt);
            }
        });
        combobox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                comboboxFocusGained(evt);
            }
        });

        checkbox.setSelected(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(combobox, 0, 93, Short.MAX_VALUE)
            .addComponent(checkbox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(checkbox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void comboboxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboboxItemStateChanged
        // TODO add your handling code here:
        if (this.selectedAction != null) {
            this.selectedAction.action(evt.getItem());
        }
    }//GEN-LAST:event_comboboxItemStateChanged

    private void comboboxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_comboboxFocusGained
        // TODO add your handling code here:
        if (this.focusGainedAction != null) {
            this.focusGainedAction.action(this);
        }
    }//GEN-LAST:event_comboboxFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkbox;
    private javax.swing.JComboBox<String> combobox;
    // End of variables declaration//GEN-END:variables

    public String getLabelName() {
        return this.checkbox.getText();
    }
}
