/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.tec02.appStore;

import com.tec02.gui.frameGui.AbsDisplayAble;
import java.awt.Color;
import java.awt.event.MouseEvent;
import javax.swing.text.DefaultCaret;

/**
 *
 * @author Administrator
 */
public class AppConsole extends AbsDisplayAble {

    private final DefaultCaret caret;

    /**
     * Creates new form AppConsole
     *
     * @param blackGroup
     * @param size
     */
    public AppConsole(boolean blackGroup, int size) {
        initComponents();
        this.caret = (DefaultCaret) this.txtAreaConsole.getCaret();
        autoCrolls();
        txtAreaConsole.setFont(new java.awt.Font("Segoe UI", 0, size));
        if (!blackGroup) {
            this.txtAreaConsole.setBackground(Color.WHITE);
            this.txtAreaConsole.setForeground(Color.BLACK);
        }
    }
    
    public AppConsole() {
        this(true, 14);
    }

    public void clear() {
        this.txtAreaConsole.setText(null);
    }

    public void set(String log) {
        this.txtAreaConsole.setText(log);
    }

    public void append(String log) {
        this.txtAreaConsole.append(log);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaConsole = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtAreaConsole.setEditable(false);
        txtAreaConsole.setBackground(new java.awt.Color(0, 0, 0));
        txtAreaConsole.setColumns(20);
        txtAreaConsole.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtAreaConsole.setForeground(new java.awt.Color(255, 255, 255));
        txtAreaConsole.setRows(5);
        txtAreaConsole.setWrapStyleWord(true);
        txtAreaConsole.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAreaConsoleMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(txtAreaConsole);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 774, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtAreaConsoleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAreaConsoleMouseClicked
        // TODO add your handling code here:
        if (evt.getButton() == MouseEvent.BUTTON3
                || (evt.getButton() == MouseEvent.BUTTON1 && evt.getClickCount() > 1)) {
            autoCrolls();
        }
    }//GEN-LAST:event_txtAreaConsoleMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAreaConsole;
    // End of variables declaration//GEN-END:variables

    private void autoCrolls() {
        this.txtAreaConsole.setCaretPosition(this.txtAreaConsole.getDocument().getLength());
        this.caret.setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);
    }
}
