/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.tec02.gui.frameGui;

import com.tec02.common.RestAPI;
import com.tec02.gui.frameGui.Component.PopupMenu;
import com.tec02.gui.frameGui.Component.MyTable;
import com.tec02.gui.panelGui.LocationFilterAddAndDelete;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class ManageEntityHaveLocation extends AbsDisplayAble {

    private final LocationFilterAddAndDelete addAndDelete;
    private final MyTable tableModel;
    private PopupMenu menu;

    /**
     * Creates new form ManagePC
     *
     * @param aPI
     * @param productGet
     * @param stationGet
     * @param lineGet
     */
    public ManageEntityHaveLocation(RestAPI aPI, String productGet, String stationGet, String lineGet) {
        super();
        initComponents();
        this.tableModel = new MyTable(tbShow);
        this.addAndDelete = new LocationFilterAddAndDelete(
                aPI, productGet, stationGet, lineGet);
        this.addAndDelete.setMyTable(tableModel);
        this.menu = new PopupMenu();
        this.tableModel.setMouseAdapter(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (menu != null && (e.getButton() == MouseEvent.BUTTON3 || e.getClickCount() > 1)) {
                    menu.show(tbShow, e.getX(), e.getY());
                }
            }
        });
        this.menu.addItemMenu("New", (e) -> {
            String input = JOptionPane.showInputDialog("input");
            if (input == null) {
                return;
            }
            addAndDelete.addNew(input);
        });
        this.menu.addItemMenu("Delete", (e) -> {
            addAndDelete.deleteSeleled();
        });
        this.pnFilter.add(this.addAndDelete);
        this.addAndDelete.update();
    }

    public MyTable getTableModel() {
        return tableModel;
    }

    public void setUrlAdd(String addUrl) {
        addAndDelete.setUrlAdd(addUrl);
    }

    public void setUrlGet(String getUrl) {
        addAndDelete.setUrlGet(getUrl);
    }

    public void setUrlDelete(String getUrl) {
        addAndDelete.setUrlDelete(getUrl);
    }

    public void setMenu(PopupMenu menu) {
        this.menu = menu;
    }

    public PopupMenu getMenu() {
        return menu;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbShow = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btFind = new javax.swing.JButton();
        pnFilter = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        tbShow.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbShow);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        btFind.setText("Find");
        btFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFindActionPerformed(evt);
            }
        });

        pnFilter.setBackground(new java.awt.Color(153, 153, 255));
        pnFilter.setLayout(new javax.swing.BoxLayout(pnFilter, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 56, Short.MAX_VALUE)
                        .addComponent(btFind, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 57, Short.MAX_VALUE))
                    .addComponent(pnFilter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(btFind)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFindActionPerformed
        // TODO add your handling code here:
        this.addAndDelete.getList();
    }//GEN-LAST:event_btFindActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
       showMenu(evt);
    }//GEN-LAST:event_formMouseClicked

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        showMenu(evt);
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void showMenu(MouseEvent evt) {
        // TODO add your handling code here:
        if (menu != null && (evt.getButton() == MouseEvent.BUTTON3 || evt.getClickCount() > 1)) {
            menu.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }

    @Override
    public void display(String titleName) {
        super.display(titleName);
        this.addAndDelete.refresh();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btFind;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnFilter;
    private javax.swing.JTable tbShow;
    // End of variables declaration//GEN-END:variables
}
