/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.tec02.gui.frameGui;

import com.tec02.common.RestAPI;
import com.tec02.gui.frameGui.Component.PopupMenu;
import com.tec02.gui.frameGui.treeFile.ChooseFile;
import com.tec02.gui.frameGui.treeFile.TreeFolder;

/**
 *
 * @author Administrator
 */
public class ShowFileGroup extends AbsDisplayAble{

    private final TreeFolder treeFolder;
    private final ChooseFile chooseFile;
    private final RestAPI api;
    private String urlGet;
    /**
     * Creates new form ShowFileGroup
     * @param api
     */
    public ShowFileGroup(RestAPI api) {
        initComponents();
        this.api = api;
        this.chooseFile = new ChooseFile();
        addSubFrame(this.chooseFile);
        this.treeFolder = new TreeFolder(tree, false);
        PopupMenu menu = this.treeFolder.getPopupMenu();
        menu.addItemMenu("upload file", (e) -> {
            this.chooseFile.display("upload file");
        });
    }
    
    private void getFile(){
        if(api == null || urlGet == null){
            return;
        }
        
    }
    
    public void clear(){
        this.treeFolder.clear();
    }
    
    public void addFile(String dir, String name){
        this.treeFolder.addFile(dir, name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tree = new javax.swing.JTree();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tree.setRootVisible(false);
        jScrollPane1.setViewportView(tree);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree tree;
    // End of variables declaration//GEN-END:variables

    public void setUrlGet(String urlGet) {
        this.urlGet = urlGet;
    }
}
